name: forwardsecrecy_dart
description: Dart implementation of forwardsec
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  cryptography: 1.4.1
  crypto: 2.1.5

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  