name: forwardsecrecy_dart
description: Dart implementation of forwardsec
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  cryptography: ^2.0.5

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  